alpha_blog4/config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "home#index"

  resources :articles

  get "signup", to: "users#new"
  post "users", to: "users#create"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories, except: [:destroy]

end

alpha_blog4/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

alpha_blog4/app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

alpha_blog4/app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25 }
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates_uniqueness_of :name
end

alpha_blog4/app/models/create_user.rb
class CreateUser < ApplicationRecord
end

alpha_blog4/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximim: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX }
  has_secure_password 
end

alpha_blog4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?


  def current_user
    @current_user ||=  User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

alpha_blog4/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #važan je redoslijed bedfore_action
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy] 

  def show
  end

  def index

    @articles = Article.paginate(page: params[:page], per_page: 5)

  end

  def new

    @article = Article.new 

  end

  def edit
  end

  def create

    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end

  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end

  end

  def destroy
    @article.destroy
    redirect_to articles_path
  
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end


end

alpha_blog4/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new 
    @category = Category.new
  end

  def index 
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully."
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully."
      redirect_to @category
    else
      render "edit"
    end
  end

  def show 
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

alpha_blog4/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to articles_path if logged_in?
  end
end

alpha_blog4/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user

    else
      flash.now[:alert] = "There was smmething wrong  with your login details"
      render "new"
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end



end

alpha_blog4/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy] 

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)

  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end

  def edit
  end

  def update

    if @user = User.update(user_params)
      flash[:notice] = "User account information was successfully updated!"
      redirect_to user_path
    else
      render 'edit'
    end

  end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}! You have successfully signed up."
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end



  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

    def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end


end

alpha_blog4/app/helpers/application_helper.rb
module ApplicationHelper

  def gravitar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravitar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravitar_url, alt: user.username, class: " pt-3 rounded shadow mx-auto d-block")
  end



end

alpha_blog4/app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <% if article.user %>
              <em> by <%= link_to article.user.username, user_path(article.user) %> </em>
            <% end %>
            <% if article.categories.any? %>
              <div class="mt-2">
                <%= render article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, lenght: 100) %></p>
            
            
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
                <%= button_to 'Delete', article_path(article), method: :delete, onclick: "return confirm('Are you sure?')", class: "btn btn-outline-danger" %>
              <% end %>
            </div>




          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

alpha_blog4/app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-10" >

      <%= render "shared/errors", obj: @article %>


      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded" , local: true) do |f| %>

        <div class="form-group row">

            <%= f.label :title, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
            </div>

        </div>

        <div class="form-group row mt-4">

          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %> 
          </div>

        </div>

        <div class="form-group row mt-4">

          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Make your selection from the list below (can be empty)" }, { multiple: true, size: 3, class: "form-select shadow rounded" } ) %>
          </div>

        </div>



        <div class="form-group row justify-content-center mt-2">
          <%= f.submit class: "btn btn-outline-light btn-lg col-2" %>
        </div>

      <% end %>

    </div>


  
    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-center mt-2 text-secondary" %>
  
  </div>

</div>

alpha_blog4/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<%= render 'form' %>
<br><br>


alpha_blog4/app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="flickr_pagination pt-4 pb-2">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render "article" %>

<div class="flickr_pagination mb-5">
  <%= will_paginate @articles, :container => false %>
</div>

alpha_blog4/app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

alpha_blog4/app/views/articles/show.html.erb


<h2 class="text-center mt-4"><%= @article.title %></h2>



<div class="container">
    <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <em> by <%= @article.user.username if @article.user  %> </em>
            <%= link_to gravitar_for(@article.user), user_path(@article.user) %>
            <% if @article.categories.any? %>
              <div class="mt-2">
                <%= render @article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-start"><%= simple_format(@article.description) %></div>
            
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <div class="btn-group" role="group" aria-label="Basic example">
                  <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
                  <%= button_to 'Delete', article_path(@article), method: :delete, onclick: "return confirm('Are you sure?')", class: "btn btn-outline-danger" %>
              </div>
            <% end %>




          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>



alpha_blog4/app/views/home/index.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

alpha_blog4/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

alpha_blog4/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Alpha Blog", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Create a new article", new_article_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "View articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>

      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
          </ul>
        </li>

        <% if logged_in? %>
        <li class="nav-item">
            <%= link_to current_user.username, user_path(current_user), class: "nav-link text-success" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, class: "btn btn-outline-secondary btn-sm mt-1 mx-1", method: :delete %>
          </li>
          <li class="nav-item">
            <% if current_user.admin? %>
            <div class= "nav-link text-danger">
              <%= "Admin" %>
            </div>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "btn btn-outline-secondary btn-sm mt-1 mx-1" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up!", signup_path, class: "btn btn-outline-success btn-sm mt-1 mx-1" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


alpha_blog4/app/views/layouts/_messages.html.erb
<div class="container pt-2">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

alpha_blog4/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>AlphaBlog4</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="d-flex flex-column">


      <%= render 'layouts/header' %>
      <div id="page-content">
        <%= render 'layouts/messages' %>  
        <%= yield %>
      </div>

    <%= render "layouts/footer" %>



    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

alpha_blog4/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
  <hr>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
  
<% end %>